### ISSUE TITLE
html code is not supported in md file?

### ISSUE THREAD

**Issue by luckypoem** [underr/yasbe#1]
hi.

i inserted some html code in a post,but after publishing,the published article still shows the html code,why?
md file natively supports html code,right?

**Comment by underr** [comment]
The markdown **mistune** library that YASBE uses doesn't parse HTML by default, I added an option for doing it in f06cbd7

Just update and set **parse_html** to **true**.

**Comment by luckypoem** [comment]
and how to paginate?
thank u

**Comment by underr** [comment]
I don't plan on adding pagination, sorry.
